// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	k8s_v1beta1 "k8s.io/api/extensions/v1beta1"
)

type IngressClient struct {
	CreateStub        func(*k8s_v1beta1.Ingress) (*k8s_v1beta1.Ingress, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 *k8s_v1beta1.Ingress
	}
	createReturns struct {
		result1 *k8s_v1beta1.Ingress
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 *k8s_v1beta1.Ingress
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IngressClient) Create(arg1 *k8s_v1beta1.Ingress) (*k8s_v1beta1.Ingress, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 *k8s_v1beta1.Ingress
	}{arg1})
	fake.recordInvocation("Create", []interface{}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createReturns.result1, fake.createReturns.result2
}

func (fake *IngressClient) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *IngressClient) CreateArgsForCall(i int) *k8s_v1beta1.Ingress {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1
}

func (fake *IngressClient) CreateReturns(result1 *k8s_v1beta1.Ingress, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 *k8s_v1beta1.Ingress
		result2 error
	}{result1, result2}
}

func (fake *IngressClient) CreateReturnsOnCall(i int, result1 *k8s_v1beta1.Ingress, result2 error) {
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 *k8s_v1beta1.Ingress
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 *k8s_v1beta1.Ingress
		result2 error
	}{result1, result2}
}

func (fake *IngressClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IngressClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
