// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/seibert-media/k8s-ingress/model"
	"k8s.io/api/extensions/v1beta1"
)

type DomainConverter struct {
	ConvertStub        func([]model.Domain) *v1beta1.Ingress
	convertMutex       sync.RWMutex
	convertArgsForCall []struct {
		arg1 []model.Domain
	}
	convertReturns struct {
		result1 *v1beta1.Ingress
	}
	convertReturnsOnCall map[int]struct {
		result1 *v1beta1.Ingress
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DomainConverter) Convert(arg1 []model.Domain) *v1beta1.Ingress {
	var arg1Copy []model.Domain
	if arg1 != nil {
		arg1Copy = make([]model.Domain, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.convertMutex.Lock()
	ret, specificReturn := fake.convertReturnsOnCall[len(fake.convertArgsForCall)]
	fake.convertArgsForCall = append(fake.convertArgsForCall, struct {
		arg1 []model.Domain
	}{arg1Copy})
	fake.recordInvocation("Convert", []interface{}{arg1Copy})
	fake.convertMutex.Unlock()
	if fake.ConvertStub != nil {
		return fake.ConvertStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.convertReturns.result1
}

func (fake *DomainConverter) ConvertCallCount() int {
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	return len(fake.convertArgsForCall)
}

func (fake *DomainConverter) ConvertArgsForCall(i int) []model.Domain {
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	return fake.convertArgsForCall[i].arg1
}

func (fake *DomainConverter) ConvertReturns(result1 *v1beta1.Ingress) {
	fake.ConvertStub = nil
	fake.convertReturns = struct {
		result1 *v1beta1.Ingress
	}{result1}
}

func (fake *DomainConverter) ConvertReturnsOnCall(i int, result1 *v1beta1.Ingress) {
	fake.ConvertStub = nil
	if fake.convertReturnsOnCall == nil {
		fake.convertReturnsOnCall = make(map[int]struct {
			result1 *v1beta1.Ingress
		})
	}
	fake.convertReturnsOnCall[i] = struct {
		result1 *v1beta1.Ingress
	}{result1}
}

func (fake *DomainConverter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DomainConverter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
