// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/seibert-media/adeia/domain"
	v1 "k8s.io/api/networking/v1"
)

type IngressCreator struct {
	CreateStub        func([]domain.Domain) *v1.Ingress
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 []domain.Domain
	}
	createReturns struct {
		result1 *v1.Ingress
	}
	createReturnsOnCall map[int]struct {
		result1 *v1.Ingress
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IngressCreator) Create(arg1 []domain.Domain) *v1.Ingress {
	var arg1Copy []domain.Domain
	if arg1 != nil {
		arg1Copy = make([]domain.Domain, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 []domain.Domain
	}{arg1Copy})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1Copy})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IngressCreator) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *IngressCreator) CreateCalls(stub func([]domain.Domain) *v1.Ingress) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *IngressCreator) CreateArgsForCall(i int) []domain.Domain {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1
}

func (fake *IngressCreator) CreateReturns(result1 *v1.Ingress) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 *v1.Ingress
	}{result1}
}

func (fake *IngressCreator) CreateReturnsOnCall(i int, result1 *v1.Ingress) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 *v1.Ingress
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 *v1.Ingress
	}{result1}
}

func (fake *IngressCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IngressCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
